//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceSubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public Medium()
        {
            this.RequestTranslations = new HashSet<RequestTranslation>();
            this.Translations = new HashSet<Translation>();
            DateAdded = DateTime.Now; 
        }
    
        public int MediaID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Year { get; set; }
        public string Discription { get; set; }
        public string URL1 { get; set; }
        public string URL2 { get; set; }
        public byte[] Picture { get; set; }
        public string File { get; set; }
        public string MediaType { get; set; }
        public int PGA_RATING { get; set; }
        public int IceUserID { get; set; }
        public int LanguageID { get; set; }
        public int GenreID { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual IceUser IceUser { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<RequestTranslation> RequestTranslations { get; set; }
        public virtual ICollection<Translation> Translations { get; set; }
    }
}
